#! /bin/sh

### BEGIN INIT INFO
# Provides:		nfcdaemon
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	NFC daemon process
### END INIT INFO

set -e

# Gleefully pilfered from:
# http://stackoverflow.com/questions/5500943/best-init-script-for-running-an-application-as-a-separate-user

#PIDFILE=/var/run/nfcdaemon.pid
USER=root

export PYTHONPATH="/usr/share"

case "$1" in
  start)
    /usr/bin/python3 /usr/share/nfcdaemon/nfcdaemon.py start
    if [ $? = 0 ]; then echo "Started nfcdaemon."; fi
    ;;
  stop)
    skill python3
    /usr/bin/python3 /usr/share/nfcdaemon/nfcdaemon.py stop
    if [ $? = 0 ]; then echo "Stopped nfcdaemon."; fi
    ;;
  restart)
    /usr/bin/python3 /usr/share/nfcdaemon/nfcdaemon.py restart
    if [ $? = 0 ]; then echo "Restarted nfcdaemon."; fi
    ;;
  status)
    if [ -f $PIDFILE ]; then
#    /usr/bin/python3 /usr/share/nfcdaemon/nfcdaemon.py start
      if [ $? = 0 ]; then
        echo "Running."
      fi
    else
      echo "Not running."
    fi
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac
exit 0
